In [1]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
%cd '/content/drive/MyDrive/EEG project/apex'
!pip install -v --no-cache-dir --global-option="--pyprof" --global-option="--cpp_ext" --global-option="--cuda_ext" ./
%cd ..

/content/drive/MyDrive/EEG project/apex
/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py:232: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.1.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/lib/python3.7/dist-packages
sysconfig: /usr/lib/python3.7/site-packages
Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/lib/python3.7/dist-packages
sysconfig: /usr/lib/python3.7/site-packages
Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/include/python3.7/UNKNOWN
sysconfig: /usr/include/python3.7m/UNKNOWN
Value for scheme.scripts does not match. Please r

In [ ]:
!pip install mne

     |████████████████████████████████| 7.4 MB 6.9 MB/s 


In [ ]:
import torch
flag = torch.cuda.is_available()
if flag:
    print("CUDA可使用")
else:
    print("CUDA不可用")
print(torch.cuda.device_count())

CUDA可使用
1


In [2]:
%cd '/content/drive/MyDrive/EEG project'

/content/drive/MyDrive/EEG project


In [4]:
from PIL import Image
import numpy as np
 
I = Image.open('毕业证.jpg')   
I_array = np.array(I)
print(type(I))
print(I_array)

<class 'PIL.JpegImagePlugin.JpegImageFile'>
[[[77 29 17]
  [76 28 16]
  [75 27 15]
  ...
  [34 25 28]
  [33 27 29]
  [34 28 28]]

 [[79 31 19]
  [78 30 18]
  [76 28 16]
  ...
  [33 24 27]
  [31 25 25]
  [31 25 25]]

 [[80 32 20]
  [80 32 20]
  [79 31 19]
  ...
  [36 27 28]
  [34 28 28]
  [33 27 27]]

 ...

 [[23 14  7]
  [22 13  6]
  [22 13  6]
  ...
  [61 33 21]
  [61 33 21]
  [61 33 21]]

 [[24 13  7]
  [23 12  6]
  [23 12  6]
  ...
  [62 34 22]
  [62 34 22]
  [62 34 22]]

 [[23 12  6]
  [23 12  6]
  [23 12  6]
  ...
  [63 35 24]
  [64 36 25]
  [64 36 25]]]


In [5]:
train_X = np.load(file="train_eeg.npy")
a = train_X[0]
a

array([[[ 1.19e-04,  7.70e-05,  2.20e-05],
        [ 1.19e-04,  1.02e-04,  5.80e-05],
        [ 1.16e-04,  1.15e-04,  7.90e-05],
        ...,
        [ 4.70e-05,  5.80e-05,  3.10e-05],
        [ 8.40e-05,  8.00e-05,  6.00e-05],
        [ 9.40e-05,  9.50e-05,  6.90e-05]],

       [[ 8.30e-05,  8.30e-05,  3.20e-05],
        [ 1.30e-04,  1.19e-04,  6.00e-05],
        [ 1.34e-04,  1.25e-04,  8.70e-05],
        ...,
        [ 3.80e-05,  5.40e-05, -3.00e-06],
        [ 4.70e-05,  6.30e-05,  2.10e-05],
        [ 5.30e-05,  5.40e-05,  1.30e-05]],

       [[ 6.80e-05,  5.50e-05,  3.20e-05],
        [ 5.40e-05,  5.80e-05,  2.50e-05],
        [ 9.20e-05,  1.03e-04,  6.20e-05],
        ...,
        [ 1.19e-04,  1.24e-04,  8.70e-05],
        [ 1.29e-04,  1.36e-04,  9.00e-05],
        [ 1.09e-04,  1.04e-04,  6.30e-05]],

       ...,

       [[ 8.00e-06, -3.00e-06, -1.60e-05],
        [-5.00e-06,  7.00e-06,  1.00e-06],
        [-3.70e-05, -1.60e-05, -2.40e-05],
        ...,
        [-3.60e-05, -2.40e

In [12]:
import torchvision
randomresizedcrop = torchvision.transforms.RandomResizedCrop(
    224,
    scale=(0.05, 0.14),
)
# trans.extend([transforms.Compose([
#   #   transforms.ToPILImage(),#转变成图像类型
#     randomresizedcrop,
#     transforms.RandomHorizontalFlip(p=0.5),
#     transforms.ToTensor(),
#     transforms.Normalize(mean=mean, std=std)])
# a = torchvision.transforms.ToPILImage()(a)
# img = randomresizedcrop(a)

In [6]:
def normalization(data):
  _range = np.max(data) - np.min(data)
  return (data - np.min(data)) / _range
def preprocess(data):
  ampl_data = data*100000
  norm_data = normalization(ampl_data)
  rgb_data = norm_data*255
  rgb_data = rgb_data.astype(np.uint8)
  return rgb_data

rgb_data = preprocess(train_X)

In [7]:
rgb_data.shape

(6960, 32, 20, 3)

In [14]:
b = torchvision.transforms.ToPILImage()(rgb_data[0])
c = randomresizedcrop(b)
d = torchvision.transforms.RandomHorizontalFlip(p=0.5)(c)

In [18]:
d.size

(224, 224)

In [ ]:
!python -m torch.distributed.launch --nproc_per_node=1 swav_impl.py --epochs 10 --base_lr 0.6 --final_lr 0.0006 --warmup_epochs 0 --batch_size 32 --size_crops 224 96 --nmb_crops 2 6 --min_scale_crops 0.14 0.05 --max_scale_crops 1. 0.14 --use_fp16 true --freeze_prototypes_niters 5005 --queue_length 3840 --epoch_queue_starts 15

/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py:164: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "The module torch.distributed.launch is deprecated "
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.run
 Please read local_rank from `os.environ('LOCAL_RANK')` instead.
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : swav_impl.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 1
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_mbokuk0a/none_0mv8h1hp
INFO:torch.distributed.elastic.agent.server.api:[default] starting

In [ ]:
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.version())
print(torch.cuda.get_device_name(0))

1.9.0+cu111
11.1
8005
Tesla P100-PCIE-16GB
